### ISSUE TITLE
DATABASE_URL??

### ISSUE THREAD

**Issue by webface** [digitalocean/supabase-on-do#10]
I followed the tutorial. It seems to work ok. What is the database url for an orm like prisma? Nothing I tried seems to work

**Comment by timothymamo** [comment]
Hi @webface.

The port for the database is currently closed on the Firewall. To connect to the database you'll need to add the following to the `digitalocean_firewall` resource block found within the `network.tf` file:
```terraform
  inbound_rule {
    protocol         = "tcp"
    port_range       = "5432"
    source_addresses = ["0.0.0.0/0", "::/0"] # All IPs allowed, suggest to reduce to smaller CIDR or your own IP
  }
```

Once this is done you can set the `DATABASE_URL` to the following (changing the password and domain with your values):
```
DATABASE_URL="postgres://postgres:[YOUR-PASSWORD]@[YOUR-SUPABASE-DOMAIN]:5432/postgres"
```

I'll create a fix for this to allow people to open the port should they wish to connect to the database directly.
