### ISSUE TITLE
Missing nginx block for graphql

### ISSUE THREAD

**Issue by zerosym** [digitalocean/supabase-on-do#12]
There is no corresponding route in the nginx conf for /graphql/v1.

The REST endpoint:
https://github.com/digitalocean/supabase-on-do/blob/1f8349c62f7ddc44881a2d9b3be1914b9c6042c1/packer/supabase/supabase.subdomain.conf#L27

This needs to be replicated with the following for GraphQL endpoint:
`location ~ ^/graphql/v1(.*)$ { ` 

The corresponding Kong path:
https://github.com/digitalocean/supabase-on-do/blob/1f8349c62f7ddc44881a2d9b3be1914b9c6042c1/terraform/files/kong.yml.tftpl#L106

**Comment by timothymamo** [comment]
Thanks for raising this @zerosym. This has now been added.
