### ISSUE TITLE
Querying supabase is timing out

### ISSUE THREAD

**Issue by liamcharmer** [digitalocean/supabase-on-do#20]
Hi I enabled the http extension, but when i try to enable supabase on my nuxt 3 project and use the client, it completely freezes. Is there anything else that I have to do? Whether thats on the droplet or?

**Comment by liamcharmer** [comment]
It worked once for a query, then it seems the Droplet or something just halts. The supabase interface no longer works

**Comment by timothymamo** [comment]
@liamcharmer could you give more information? Output of any logs/errors? Where and how are you running your nuxt3 project?

From the [example app](https://github.com/digitalocean/do-app-with-supabase) using App Platform I didn't have any issues querying the Supabase instance.

**Comment by liamcharmer** [comment]
> 

Is there a way to view the logs on the droplet at all? I haven't got any logs on the server side, running the nuxt 3 project on a Digital ocean apps but this is me doing it via localhost at the moment

**Comment by timothymamo** [comment]
If you've got [ssh enabled](https://github.com/digitalocean/supabase-on-do/blob/main/terraform/variables.tf#L129) (defaults to true), once you ssh in the droplet you can run `docker logs <container name>` to see the logs for each container.

I'd also check the [swag](https://github.com/digitalocean/supabase-on-do/blob/main/packer/supabase/docker-compose.yml#L8) container logs. You might have to exec into the container to check logs for each component (fail2ban and nginx). You can do this by running `docker exec -it /bin/bash` and once in the container, accessing the log files for each component at the `/config/log` directory.

**Comment by liamcharmer** [comment]
Ill give it a check now! Thank you so much for getting back to me here!! I appreciate the time!!

**Comment by liamcharmer** [comment]
I've got into the droplet, however running ``docker exec -it /bin/bash`` returns the error ```"docker exec" requires at least 2 arguments.
See 'docker exec --help'.

Usage:  docker exec [OPTIONS] CONTAINER COMMAND [ARG...]

Execute a command in a running container```

**Comment by liamcharmer** [comment]
ah sorry, -it swag /bin/bash

**Comment by liamcharmer** [comment]
It seems the fail2ban is banning my IP address for some reason @timothymamo

**Comment by liamcharmer** [comment]
Looking into it a bit deeper, it may be the RLS i have configured as in one of the routes I get a 401, even though it should be public. Whereas another table and its routes when I select it works fine.

**Comment by timothymamo** [comment]
If fail2ban is blocking your IP you can configure it to ignore your IP. You can find more information on how to do this [here](https://github.com/linuxserver/fail2ban-confs/blob/master/README.md). But it's weird that fail2ban is doing this without cause.

**Comment by liamcharmer** [comment]
I've just had a look at the nginx access logs, it seems that for some routes querying tables it is receiving a 401, and as soon as that happens either the droplet hangs or the ban initiates and i cannot query the server anymore

**Comment by liamcharmer** [comment]
@timothymamo ... it was my silly mistake. On my project, i did use the supabase initially with their services. So my localhost had cookies and localstorage set with the previous connections. Even though I changed my .env file, it didnt remove the cookies and hence causing the 401 error with the authentication and probably causing the ban. 

Apologies for taking your time!!

And thank you for the help and guidance!!!!!
