### ISSUE TITLE
Magic Link SSL Certificate

### ISSUE THREAD

**Issue by liamcharmer** [digitalocean/supabase-on-do#22]
Is there something in the domain config I am supposed to do? I have nameservers with Digital Ocean however with the magic link it generates the correct domain

but starts with 

``http://url2892.``

When I go to the link I get the below error regarding SSL. 

<img width="473" alt="Screenshot 2023-03-04 at 15 52 32" src="https://user-images.githubusercontent.com/10831349/222915825-d57c6f36-b6b6-48c5-806f-5ea6158662fa.png">

is there something i need to config?

**Comment by timothymamo** [comment]
Is this the magic link to access your application (similar to what is created in the [sample app](https://github.com/digitalocean/do-app-with-supabase))? If that's the case you need to set the [`site_url`](https://github.com/digitalocean/supabase-on-do/blob/main/terraform/variables.tf#L51) variable to your applications domain.

If you're running stuff locally, you might have to set the variable to localhost (it will give you an ssl error as the site url variable sets the address to [https](https://github.com/digitalocean/supabase-on-do/blob/main/terraform/files/.env.tftpl#L58))

**Comment by liamcharmer** [comment]
So the site using supabase is

https://createyourzen.app

and an example of a password recovery link is
http://url2892.createyourzen.app/ls/click?upn=oYV1-2BqJbqS0ORlLWtBz2G-2B3yGKpjFD2RFjJ8xeyEhdAyi3JWbDgJL7FZh4xOhnYfnrmGMXnesTblP5AUUu5p9KGJvc8IjDEPPuVhySoBLfGo72LZ8umB5gfGene0DxR09FIb-2FDNGej8L9MyMBC0YcT-2BIwasQC0yXJXZUN6SuAi613WEC0lL66tDCb1ULPOBpUi1R0Xhsov8RW5naIqzKHHWkQ57WTNlhrIs-2BjnXPhw9Iv4PP5lqnX4F4eT8pLm-2ByyXmn_jKvaZ5iIu-2FKDc1bqrDD-2FnxxctSzwUVJGpnCT4x9vOkRKw9AYWJA79K2S6359hJcftw4n1hjjvonUeY321-2Fh5mKANVx0eikj98nSwA6-2Fw5qexF-2BuBa-2BTeuQ1v7mOuvOszCkKcpYumR9CEZW07OW75Fe1hn3gHCX8ciGEKEGfSTWt4KqtzaV2OuuQWr0cASPlQHpxpRcx-2BzWJphl0MDwGuBQ-3D-3D

**Comment by liamcharmer** [comment]
I haven't seen the url2892 thing before ever, is this something I have to change when I was setting up the docker stuff etc via the tutorial? @timothymamo

**Comment by timothymamo** [comment]
Not sure where `url2892` is coming from. All you need to do is set the variables within the [`tfvars` file](https://github.com/digitalocean/supabase-on-do/blob/main/terraform/terraform.tfvars.example).

As long as you are referencing your supabase instance with the your `<YOUR_SUPABASE_URL>` and `<YOUR_SERVICE_ROLE_KEY>` within your application it should work.

**Comment by liamcharmer** [comment]
Within the application aren't we supposed to use the ANON_KEY instead of the SERVICE_ROLE key??

**Comment by timothymamo** [comment]
You're right sorry, should be ANON_KEY.

**Comment by liamcharmer** [comment]
That's all fine I honestly have no idea about this type of stuff! All that is set fine in the tfvars file I have 

```
region    = "ams3"
domain    = "createyourzen.app"
timezone  = "Europe/London"
auth_user = "*****"
site_url  = "supabase.createyourzen.app"
```

is site_url supposed to be the subdomain you access supabase from right? (as that is currently working fine)

**Comment by liamcharmer** [comment]
Ahhh that's where I went wrong, the site_url also had to match and be the applications URL. Not what I intended for the supabase application to work on

https://github.com/digitalocean/supabase-on-do/blob/main/terraform/README.md#:~:text=site_url,in%20the%20format.

**Comment by timothymamo** [comment]
Ahhhh ok, the `site_url` should be `createyourzen.app` (no need to add https:// as that is added automatically)

**Comment by liamcharmer** [comment]
@timothymamo sorry for being an absolute silly person and not fully reading into the docs... Once I update the vars am i able to apply and run again for it to be updated to be updated on current droplet? Or do I have to spool up a new droplet

**Comment by timothymamo** [comment]
For everything to apply when changing environment variables you'll need to either spin up another droplet or restart the containers within the droplet.

**Comment by liamcharmer** [comment]
I'll spin up a new droplet! Thank you so much @timothymamo i'll see how this gets on and works

Thank you for your time on a saturday!!!

**Comment by timothymamo** [comment]
Hopefully it all works out, enjoy your Saturday. Feel free to reach out whenever, but I'll log off for the weekend 😃
