### ISSUE TITLE
different E-Mail Provider

### ISSUE THREAD

**Issue by WebPirat** [digitalocean/supabase-on-do#23]
Hello, first of all thanks for the awesome work!

I am on the road so the curiosity got to me maybe its really easy...
Hosting my own EMail servers alreadyis it hard to change to your own Servers or is it with DO not possible ?

Thanks for your time
Best Regards

**Comment by timothymamo** [comment]
Hey @WebPirat thanks for the kind words.

It is possible to use your own email server with supabase, but you will have to change/remove a few things within this repo.

Namely you'd have to:
1. Remove the Sendgrid provider, terraform sendgrid configuration and varibales ([provider](https://github.com/digitalocean/supabase-on-do/blob/main/terraform/provider.tf#L25), [config](https://github.com/digitalocean/supabase-on-do/blob/main/terraform/sendgrid.tf))
2. Change the smtp variables accordingly ([smtp vars](https://github.com/digitalocean/supabase-on-do/blob/main/terraform/variables.tf#L171-L229))
3. Set the appropriate api key/token/password to connect to the email server (You can use the [sendgrid API veriable](https://github.com/digitalocean/supabase-on-do/blob/main/terraform/variables.tf#L25))
4. Change the variable for `TF_SMTP_PASS` to your server api key/token/password ([TF_SMTP_PASS](https://github.com/digitalocean/supabase-on-do/blob/main/terraform/locals.tf#L129))

I believe that should be all that needs to be changes, but haven't tested it out.

Hope this works for you :)
Tim
