### ISSUE TITLE
Terraform sendgrid error

### ISSUE THREAD

**Issue by socketopp** [digitalocean/supabase-on-do#31]
I'm receiving the following error when running `terraform apply` for the first time. 
I'm on Windows and executed both with CMD and Bash for windows but neither works. 

Running the script manually result in this:

```
$ cp ./files/sender-verification.sh.tmpl ./files/sender-verification.sh && chmod +x ./files/sender-verification.sh && ./files/sender-verification.sh
./files/sender-verification.sh: line 7: API: unbound variable
``` 
I managed to run the file `files/sender-verification.sh` locally though!

```
  Enter a value: yes

sendgrid_link_branding.this: Modifying... [id=3124253]
null_resource.sendgrid_single_sender: Destroying... [id=3843209286544504017]
sendgrid_domain_authentication.this: Modifying... [id=17565526]
null_resource.sendgrid_single_sender: Destruction complete after 0s
null_resource.sendgrid_single_sender: Creating...
null_resource.sendgrid_single_sender: Provisioning with 'local-exec'...
null_resource.sendgrid_single_sender (local-exec): (output suppressed due to sensitive value in config)
null_resource.sendgrid_single_sender (local-exec): (output suppressed due to sensitive value in config)
null_resource.sendgrid_single_sender (local-exec): (output suppressed due to sensitive value in config)
sendgrid_link_branding.this: Modifications complete after 1s [id=3124253]
sendgrid_domain_authentication.this: Modifications complete after 2s [id=17565526]
╷
│ Error: local-exec provisioner error
│
│   with null_resource.sendgrid_single_sender,
│   on sendgrid.tf line 6, in resource "null_resource" "sendgrid_single_sender":
│    6:   provisioner "local-exec" {
│
│ Error running command 'cp ./files/sender-verification.sh.tmpl ./files/sender-verification.sh && chmod +x
│ ./files/sender-verification.sh && ./files/sender-verification.sh': exit status 1. Output: '.' is not recognized as an
│ internal or external command,
│ operable program or batch file.
│
╵
```

SOLVED:

In Windows, you can modify the command to use the backslash character instead of the forward slash character to separate directory names, and use the .\ notation to refer to the current directory. 

`command = "copy .\\files\\sender-verification.sh.tmpl .\\files\\sender-verification.sh && chmod +x .\\files\\sender-verification.sh && .\\files\\sender-verification.sh"`

**Comment by 0reo** [comment]
Know this is an old issue, but thought I had run into this problem and it give me a bit of a run-around.

~~Forward slashes work fine in Windows, both in Git Bash and CMD~~ I was incorrect, they worked in the terminal, but I did indeed get the `Output: '.' is not recognized` error after running `terraform apply`

```
Oreo@DESKTOP-L0KKT3Q /e/dev-personal/supabase-on-do/terraform (updates)
$ ls ./files
digitalocean.ini.tftpl  kong.yml.tftpl  sender-verification.sh*  sender-verification.sh.tmpl*  supabase.subdomain.conf.tftpl

Oreo@DESKTOP-L0KKT3Q /e/dev-personal/supabase-on-do/terraform (updates)
$ cmd
Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

E:\dev-personal\supabase-on-do\terraform>ls ./files
digitalocean.ini.tftpl  kong.yml.tftpl  sender-verification.sh  sender-verification.sh.tmpl  supabase.subdomain.conf.tftpl
```



The error `./files/sender-verification.sh: line 7: API: unbound variable` likely happened because `cp ./files/sender-verification.sh.tmpl ./files/sender-verification.sh && chmod +x ./files/sender-verification.sh && ./files/sender-verification.sh` was run manually.  The `API` environment variable is defined in `sendgrid.tf`, which I believe populates it into `sender-verification.sh.tmpl` before it gets copied.
