### ISSUE TITLE
Chrome says "This site can’t be reached"

### ISSUE THREAD

**Issue by ivan006** [digitalocean/supabase-on-do#41]
This site can’t be reached supabase.[my domain] took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_TIMED_OUT

**Comment by timothymamo** [comment]
Hi @ivan006 will need more info if you need help with this as the above doesn't explain much. What's your setup? Any issues when running terraform? What can you see on the DigitalOcean console UI?

**Comment by ivan006** [comment]
the only container with issues is "supabase-imgproxy" but it is permanently not working but the system works when i restart it in spite of supabase-imgproxy not working. So supabase-imgproxy in my case doesn't seem essential. But the weird thing is the system will work fine for a while then when it will stop out of the blue and then when i run `docker ps -a` it says everything else is working fine even while the system is obviously borked  

i dont have a lot of ram this is my droplet spec
`2 GB Memory / 25 GB Disk + 25 GB / AMS3 - Ubuntu supabase-20230728204426`
But im wondering why it doesnt give any clear sign of error for me to say `ah that is the problem` the only error i get is that the system is unreachable until i restart it

**Comment by timothymamo** [comment]
Hi @ivan006, could you:

1. Explain what you have changed from the packer and terraform code from the repo and what the output was.
      * Seeing that multiple people have managed to run the code successfully, I would first start to understand what changes have been made to the code. 
2. Run a `docker logs` on each container to get the logs of all the containers when the system is not working.

Also unsure as to why you think that `supabase-imgproxy` is not essential for you. Are you planning on storing images? If so the container `supabase-storage` uses this to optimize images.

**Comment by ivan006** [comment]
Image support would create more holistic app however not having image support shouldn't lead to the above behavior (site unreachble). Unless i'm missing something.  I ran docker logs on all the containers and especially scrutinized the logs within the period that i new the app stopped working but nothing telling.

I only changed things that are ignored by the gitignore

the gitignore
```
.DS_Store
.terraform
.idea/
.env.bkp
*.lock.hcl
terraform.tfvars
*.tfstate*
sender-verification.sh
supabase.auto.pkrvars.hcl
.vscode/
```

**Comment by ghost** [comment]
Hi @ivan006 I don't understand your comment about image support.

I cannot help if you don't supply what I ask for and you keep on saying everything works but site is not working. Trying to help to debug the issue with no resources or information is almost impossible.

**Comment by ivan006** [comment]
Hi @timothymamo and @Unibond7,

Firstly, I appreciate your patience and assistance in this matter. I understand the need for comprehensive details to troubleshoot the issue effectively, and I'll do my best to provide as much clarity as possible.

Regarding the `supabase-imgproxy` container, I understand its relevance especially in conjunction with `supabase-storage` for image optimization. My primary concern was the perception that even if `supabase-imgproxy` were malfunctioning, it shouldn't render the entire system unreachable. I acknowledge, however, that containers can have interdependencies, and I'm open to insights on this front.

To clarify further on my setup:
1. I've ensured that I only modified files and configurations that are listed in `.gitignore`.
2. I've been scrutinizing the logs, especially focusing on the period when I observed the system going down. As of now, I haven't identified any overtly telling signs or errors.
3. My DigitalOcean droplet has specifications of 2 GB Memory / 25 GB Disk. I'm keen to understand if resource constraints could be playing a part in this. I'll monitor the droplet's resource usage more closely to identify any potential memory pressure or spikes.

In light of the above, I'd appreciate any further guidance or steps you might recommend to diagnose and address the issue. I value your expertise and time, and I'm committed to working collaboratively to resolve this.

Thank you for your understanding.

**Comment by timothymamo** [comment]
Hey @ivan006, thanks for the message.

I'm not an expert at Supabase, so unsure if a failing container would make the system unreachable, although I would expect that this might be an option. In fact when I was creating this project and testing things out, when not having a bucket connected to the system things would stop working even though you'd think that not having a bucket attached should not do this.

The size of the droplet was the same as what I have used, and is the default setting. I have successfully deployed the system with the same size droplet, so it is unlikely that this is the issue. Only exception I can think of is having the droplet flooded with requests.

I suggest looking into why the container `supabase-imgproxy` is crashing as your first port of call as that seems to be one thing that differs from a working system.

**Comment by ivan006** [comment]
Hi @timothymamo,

Thank you for your insights. Let me provide some clarification regarding the intermittent behavior I'm observing:

The system works intermittently. The cycle I've noticed is that it functions as expected, then becomes unreachable. Restarting my droplet brings it back to a reachable state, but only for a while before the cycle repeats.

I fully acknowledge the concerns about the supabase-imgproxy container. What I'd like to emphasize is that even when the system is reachable and functioning, the supabase-imgproxy container has consistently been non-operational. In essence, the system has been able to operate multiple times despite this particular container never having worked in my setup.

Below are the logs from docker ps -a, showcasing the state of my containers. It's noteworthy that the status of these containers remains consistent, irrespective of whether the system is reachable or not.


```
Last login: Wed Aug  9 10:55:55 2023 from 102.220.209.217
root@supabase-droplet:~# docker ps -a
CONTAINER ID   IMAGE                              COMMAND                  CREATED       STATUS                       PORTS                                                                                                      NAMES
e5dc1ce000f1   supabase/storage-api:v0.40.4       "docker-entrypoint.s…"   11 days ago   Up About an hour (healthy)   5000/tcp                                                                                                   supabase-storage
4522857e9eed   supabase/realtime:v2.10.1          "/usr/bin/tini -s -g…"   11 days ago   Up About an hour (healthy)                                                                                                              realtime-dev.supabase-realtime
ed2f0005efdf   supabase/postgres-meta:v0.66.3     "docker-entrypoint.s…"   11 days ago   Up About an hour (healthy)   8080/tcp                                                                                                   supabase-meta
37d76061775e   supabase/gotrue:v2.62.1            "gotrue"                 11 days ago   Up About an hour (healthy)                                                                                                              supabase-auth
3a992cc21a0b   postgrest/postgrest:v10.1.2        "/bin/postgrest"         11 days ago   Up About an hour             3000/tcp                                                                                                   supabase-rest
f8e746c3e996   darthsim/imgproxy:v3.13            "imgproxy"               11 days ago   Exited (255) 11 days ago     8080/tcp                                                                                                   supabase-imgproxy
d90eb8497ca0   supabase/postgres:15.1.0.90        "docker-entrypoint.s…"   11 days ago   Up About an hour (healthy)   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                  supabase-db
2ef6cd771761   kong:2.8.1                         "/docker-entrypoint.…"   11 days ago   Up About an hour (healthy)   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 8001/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp, 8444/tcp   supabase-kong
ebc553eae838   supabase/edge-runtime:v1.5.2       "edge-runtime start …"   11 days ago   Up About an hour             0.0.0.0:32768->9000/tcp, :::32768->9000/tcp                                                                supabase-edge-functions
db9cf9913bba   supabase/studio:20230622-d8395eb   "docker-entrypoint.s…"   11 days ago   Up About an hour (healthy)   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                  supabase-studio
ce01fff19ad8   lscr.io/linuxserver/swag:2.2.0     "/init"                  11 days ago   Up About an hour             0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                                   swag
root@supabase-droplet:~# ^C
root@supabase-droplet:~#
```

Given the above, I would appreciate any guidance on potential next steps or areas of focus. I understand the importance of resolving the supabase-imgproxy issue, but I also want to explore any other underlying factors that might contribute to the system's instability.

Thank you for your patience and support.

**Comment by ivan006** [comment]
Hey all,

I've made an interesting discovery regarding the "unreachable" behavior of my system. After some testing and troubleshooting, it seems that I was getting temporarily blocked due to repeated failed authentication attempts, specifically from using an expired JWT token.

Here's what I found:

After I stopped hitting the server with an expired token, the system was stable and responsive for a good hour.
When I began making requests with the expired token again, within minutes, the system became "unreachable" from my PC.
Interestingly, when I tried accessing the app from a different network (my mobile data), it worked perfectly. This suggests it's not a system-wide failure, but rather my IP address being temporarily blocked.
This kind of behavior is typically a security measure to prevent brute-force attacks or other types of malicious activities. It's possible that repeated failed attempts using the expired token were perceived as suspicious, leading to a temporary IP block.

Going forward, I'll implement mechanisms to better handle token expiration to avoid unintentionally triggering such blocks. I thought I'd share this discovery here, in case someone else encounters a similar issue in the future.

Thanks for all the support and guidance throughout this debugging process!

**Comment by ivan006** [comment]
Closing

**Comment by timothymamo** [comment]
This must have been shown in the logs (hence me asking for the logs) of the `swag` container as it also contains `fail2ban` as described in the [Docker Compose](https://github.com/digitalocean/supabase-on-do/tree/main#docker-compose) section of the documentation.

**Comment by ivan006** [comment]
My apologies for the oversight. I mistakenly ran:
```
docker logs swag 2>&1 | grep "09/Aug/2023:10:[3-4]"
```
instead of the correct:
```
docker logs swag 2>&1 | grep "2023-08-09 10:[3-4]"
```
Thank you for pointing it out.
Here are the correct logs from swag
 
 ```
 root@supabase-droplet:~# docker logs swag 2>&1 | grep "2023-08-09 10:[3-4]"
2023-08-09 10:30:07,706 fail2ban.configreader   [348]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
```

**Comment by ghost** [comment]
Be aware that when filtering logs like this you might be using the incorrect timezone as containers might be logging using UTC rather than your local timezone. If you really want to filter results I would grep for `ERROR` and `WARNING` rather than time as these might have occurred way before you notice the issue. Assuming that the error occurs only when you notice it might mean you miss out on important logs.
