### ISSUE TITLE
wrong droplet image id

### ISSUE THREAD

**Issue by matart15** [digitalocean/supabase-on-do#52]
`packer build .`

```
==> digitalocean.supabase: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422  You specified an invalid image for Droplet creation.
```

https://github.com/digitalocean/supabase-on-do/blob/main/packer/supabase.pkr.hcl#L28

No `"ubuntu-22-10-x64"`. maybe `"ubuntu-23-10-x64"`?

<img width="404" alt="Screenshot 2024-04-01 at 22 05 35" src="https://github.com/digitalocean/supabase-on-do/assets/17027219/cf0ae3de-5919-4b12-839e-f8b9b94097fb">

**Comment by 0reo** [comment]
needs to be 22.04, docker-ce is not available on 23.10
