### ISSUE TITLE
Hook updates

### ISSUE THREAD

**Issue by SteveChurch** [digitalocean/supabase-on-do#6]
@timothymamo i see your repo regularly updates the supabase image. What hooks are you using to do this? Have you got a nightly action?

**Comment by timothymamo** [comment]
Hey @SteveChurch unfortunately nothing that fancy. I've got a watch on the [docker](https://github.com/supabase/supabase/tree/master/docker) directory within the [supabase/supabse](https://github.com/supabase/supabase) repo via [GitHub File Watcher](https://app.github-file-watcher.com/) which notifies me whenever there is a change to any of the files, which I then manually update and push directly to main (I know, I know). 

You could also use [commit-hawk](https://github.com/jesalg/commit-hawk) as an app in GitHub or [RenovateBot](https://docs.renovatebot.com/) or [dependaBot](https://github.com/dependabot/dependabot-core) to look for changes in docker dependencies. The bots could even auto merge for you if you're feeling lucky. Currently not using these bots as the versions in the docker-compose file are different to the latest being pushed and I want to keep as much parity with what Supabase has in their repo.

I do have pre-commit hooks which format files and update terraform docs which run every time I commit locally. If a change does happen I then have an alias in my terminal that commits with a standard message. `alias ghooks='git add .; gcmsg "Adding changes by hooks"`.

Hope this helps.

**Comment by SteveChurch** [comment]
And there was me thinking you had something clever set up 😉  - I might use DependaBot, I've used both in the past but have nothing set up yet for this project. 

Thanks for the feedback. 👍🏻
