### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by SteveChurch** [digitalocean/supabase-on-do#7]
Correct me if I'm wrong, but I haven't seen any migration handling. AFAIK there is an open issue regarding the Supabase CLI having this recently removed where you can set a target supabase api, whereas now it's '--project' which is less than ideal for self hosted. 

I was thinking on my fork of pushing my migrations up to a DO space where they can then be actioned / triggered within a migrations container. Or have a GitHub Action detect migrations files and run the necessary commands within the PG container. 

What are your thoughts on this?

**Comment by timothymamo** [comment]
Ahhh good question, I'm actually looking in to that now. So I'll keep you updated if I have anything concrete.

According to how you are doing updates of the containers (are you creating a new snapshot? are you sshing into the Droplet, modifying the `docker-compose.yml` file and running `docker compose up -d`? something else) there are multiple ways of doing this.

I'm a fan of separation of privileges/tasks so I'd lean towards a migration container.

**Comment by SteveChurch** [comment]
Thanks for getting back to me, 

I did a DEEP dive into this late last night, I ended up falling asleep trying to figure out how the integrated migrations work with Superbase. It looks like they already have some migrations directories which look through the migrations, but adding our own migrations into that directory could break some of the flow. 

I did read that they are fully aware migrations can be a Pain In The A** for people self-hosting, but no one really seems to have provided a concrete approach. Or at least I haven't found these yet. 

In response to your question I am creating new snapshots each time I have any infra changes using your packer example. 

There is a `migrate.sh` I found in one of their repos, but I was thinking if the `supabase-cli` was/is installed within the Postgres container then potentially a migration can be run there using the pre-existing tooling. 

A final thought, I might use `pg-migrate` in a separate container but just load in the migrations produced from the CLI from my local dev. Or even better, a GitHub Action to detect migration files and run them via `pg-migrate`

**Comment by SteveChurch** [comment]
Ahha. Thought I would take a quick look at this today, the migration script within the `supabase/postgres` repo is quite simple, I think I will go with a container which pulls a copy of the repo where my migrations are housed and use `dbmate` like is used in this script: https://github.com/supabase/postgres/blob/91f2a2278f112df816ecf45ea49f4ccfdc7a0e6f/migrations/db/migrate.sh

Maybe at some point create some sort of trigger once a build has been successful, I guess the migration could run part of a GitHub Action but would prefer to keep database connections to the containers locked down.

**Comment by timothymamo** [comment]
Closing this issue as we have an ongoing [discussion](https://github.com/digitalocean/supabase-on-do/discussions/15) regarding migrations.
