### ISSUE TITLE
Edge Functions

### ISSUE THREAD

**Issue by SteveChurch** [digitalocean/supabase-on-do#9]
I have been doing plenty of reading up to try and get the whole Edge Functions side of things working. It looks like Supabase host their Edge Functions on Deno Deploy, however, there seems to be little documentation on how to replicate what they have set up. 

It seems that there is a [Functions Relay](https://github.com/supabase/functions-relay) in place, but I am just trying to figure out the rest to get this working. 

@timothymamo have you had any further thoughts on this? It would be good to tap into some of your knowledge if you have at any point got the Deno Edge Functions working with the self-hosted version of Supabase.

**Comment by timothymamo** [comment]
@SteveChurch, I haven't used Edge Functions on Supabase yet, so cannot be of much help currently. This might be something for the Supabase team, but I'll have a look and see what I can figure out and keep you updated.

But from the looks of it this is a known issue according to this [Issue](https://github.com/supabase/supabase/issues/10319) on the Supabase repo

**Comment by SteveChurch** [comment]
Thanks @timothymamo - I have managed to migrate all of my Edge Functions and turn them into Database functions. Thankfully I can do everything I need directly in SQL even down to API calls. this negates the need for me, however, hopefully soon enough they will release more of their features to the self hosted solution. 

https://supabase.com/docs/guides/database/functions

**Comment by timothymamo** [comment]
Awesome, thanks for the update @SteveChurch and glad that you got it to work.
